// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ludguqvdobqdvvcsrlnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZGd1cXZkb2JxZHZ2Y3NybG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MzYyNzUsImV4cCI6MjA1OTMxMjI3NX0.Q_O2QJXxTwrVD9VRJMm8XYrc3CYrlZqejNvC29UH9pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);